### ISSUE TITLE
+AS bug

### ISSUE THREAD

**Issue by rahryanrah** [alexbonjour/clicker-lister#23]
When i post my save in, even tho i can trans for +14, it says +0.

**Outsiders**: Ponyboy (12);

**Ancients**: Bhaal (175), Fragsworth (175), Argaiv (175), Mammon (163), Mimzee (163), Solomon (155), Juggernaut (63), Dora (11), Kumawakamaru (11);

**Not Summoned**: Atman, Berserker, Bubos, Chawedo, Chronos, Dogcog, Energon, Fortuna, Hecatoncheir, Kleptos, Libertas, Morgulis, Pluto, Revolc, Siyalatas, Sniperino, Vaagur;

**Gilded Heroes**: Samurai (47), Dread Knight (47);

**Misc**: AS (12 *+0*); TP (1.06%); HS (31,925; Spent on Ancients/Rerolls: 215,131/1,440; Total: 248,496) Zone(Now HZE Best): 717 1,004 1,004; Ascensions: 17; Immortal Damage: 295,044; Rubies: 66; Forge Cores: 320; Total Relics Found: 16; Achievements: 50%; 

**Time**: Since Start: 25 days; Since Transcension: 16 days; Since Ascension: 0h 51m; 

**Total Relic Bonuses**: 

* +4.59 Dogcog 
* +2.00 Fortuna 
* +2.00 Dora 
* +19.00 Sniperino 
* +2.00 Argaiv 
* +4.00 Mimzee 
* +2.26 Solomon 

if you need my save (just in-case if you need to test if its something in my save for some odd reason) ill post it in a pastebin http://pastebin.com/jgThmCMh (dont question my playstyle)

**Comment by alexbonjour** [comment]
Thanks for the info.  I'm debugging now.

**Comment by alexbonjour** [comment]
The bug is fixed.   Thanks @rahryanrah for the report and the save file.
