### ISSUE TITLE
 clicker-lister/common/saveDecoder.js error

### ISSUE THREAD

**Issue by thetyraen** [alexbonjour/clicker-lister#24]
Hi !

There is a little error l36 of  clicker-lister/common/saveDecoder.js 
 if (dataHash = hash) return data;
needs to be
 if (dataHash == hash) return data;
== is used for comparation

PS : I made some test and I alway have "hash is bad" with this modif, hash and dataHash are not equal ...

Good luck !

**Comment by alexbonjour** [comment]
Fixed as suggested.  Thanks @thetyraen
